name: Build Android Kernel

on:
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y build-essential ncurses-dev bison flex libssl-dev libelf-dev clang
          # Add any other required dependencies

      - name: Clone kernel source
        run: git clone https://github.com/qliazar/htc_kernel_wildfire.git --depth=1

      - name: Get toolchains
          wget https://android.googlesource.com/platform/prebuilt/+archive/6c89c6601a699707500003b782406482c4c3050b/linux-x86/toolchain/arm-eabi-4.4.3.tar.gz
          tar -xvf arm-eabi-4.4.3.tar.gz
        # Use a specific action or manual commands to fetch AOSP Clang/GCC toolchains
        # Example using a common approach:
        # wget ... toolchain download link ...
        # tar -xvf ...
        # export PATH="..."

      - name: Build kernel
        run: |
          cd htc_kernel_wildfire
          export ARCH=arm
          export SUBARCH=arm
          export CROSS_COMPILE=/arm-eabi-4.4.3/bin/arm-eabi-
          make cyanogenmod_wildfire_defconfig
          make -j$(nproc)

      - name: Upload kernel artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-kernel
          path: <kernel-source-dir>/arch/arm64/boot/zImage # Adjust path as needed
